// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlZxfatdEbbs-P9-vlNU4K8vSsGI23TQs',
    appId: '1:929344632687:web:9779a12c7f82daad1f1a9a',
    messagingSenderId: '929344632687',
    projectId: 'hostelpergamino-3739c',
    authDomain: 'hostelpergamino-3739c.firebaseapp.com',
    storageBucket: 'hostelpergamino-3739c.appspot.com',
    measurementId: 'G-PWGPTMXNH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5hRnagltdiR2mYgg7vk5UNQiLalopcgw',
    appId: '1:929344632687:android:f15ee2060c5459791f1a9a',
    messagingSenderId: '929344632687',
    projectId: 'hostelpergamino-3739c',
    storageBucket: 'hostelpergamino-3739c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ9PLKvfRsPG5T8pi-gciG2Vr567a1OMk',
    appId: '1:929344632687:ios:7675060b2a005fdf1f1a9a',
    messagingSenderId: '929344632687',
    projectId: 'hostelpergamino-3739c',
    storageBucket: 'hostelpergamino-3739c.appspot.com',
    iosClientId: '929344632687-lbplnv0okjemvvceoa73mgdqee0a551f.apps.googleusercontent.com',
    iosBundleId: 'com.g4g.hostel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ9PLKvfRsPG5T8pi-gciG2Vr567a1OMk',
    appId: '1:929344632687:ios:7675060b2a005fdf1f1a9a',
    messagingSenderId: '929344632687',
    projectId: 'hostelpergamino-3739c',
    storageBucket: 'hostelpergamino-3739c.appspot.com',
    iosClientId: '929344632687-lbplnv0okjemvvceoa73mgdqee0a551f.apps.googleusercontent.com',
    iosBundleId: 'com.g4g.hostel',
  );
}
